In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv('CVD.csv')

In [4]:
dataset= dataset.drop('patientid',axis=1)

In [5]:
dataset

,age,gender,chestpain,restingBP,serumcholestrol,fastingbloodsugar,restingrelectro,maxheartrate,exerciseangia,oldpeak,slope,noofmajorvessels,target
0,53,1,2,171,0,0,1,147,0,5.3,3,3,1
1,40,1,0,94,229,0,1,115,0,3.7,1,1,0
2,49,1,2,133,142,0,0,202,1,5.0,1,0,0
3,43,1,0,138,295,1,1,153,0,3.2,2,2,1
4,31,1,1,199,0,0,2,136,0,5.3,3,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,48,1,2,139,349,0,2,183,1,5.6,2,2,1
996,47,1,3,143,258,1,1,98,1,5.7,1,0,0
997,69,1,0,156,434,1,0,196,0,1.4,3,1,1
998,45,1,1,186,417,0,1,117,1,5.9,3,2,1
999,25,1,0,158,270,0,0,143,1,4.7,0,0,0

In [6]:
#checking for null values
dataset.isnull().sum()

age                  0
gender               0
chestpain            0
restingBP            0
serumcholestrol      0
fastingbloodsugar    0
restingrelectro      0
maxheartrate         0
exerciseangia        0
oldpeak              0
slope                0
noofmajorvessels     0
target               0
dtype: int64

In [16]:
table = pd.DataFrame(index=['mean','median','mode','Q1','Q2','Q3','Q4','IQR','lesser out'
                           ,'min','greater out','max',"kurtosis",'skew','var','std'],columns=dataset.columns)

In [17]:
table

,age,gender,chestpain,restingBP,serumcholestrol,fastingbloodsugar,restingrelectro,maxheartrate,exerciseangia,oldpeak,slope,noofmajorvessels,target
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
median,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Q1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Q2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Q3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Q4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IQR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lesser out,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
greater out,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
kurtosis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
skew,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
var,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
for clnm in dataset.columns:
    table[clnm]['mean']= dataset[clnm].mean()
    table[clnm]['median']= dataset[clnm].median()
    table[clnm]['mode']= dataset[clnm].mode()[0]
    table[clnm]['Q1']= dataset.describe()[clnm]['25%']
    table[clnm]['Q2']= dataset.describe()[clnm]['50%']
    table[clnm]['Q3']= dataset.describe()[clnm]['75%']
    table[clnm]['Q4']= dataset.describe()[clnm]['max']
    table[clnm]['min']= min(dataset[clnm])
    table[clnm]['max']= max(dataset[clnm])
    table[clnm]['IQR']=table[clnm]['Q3'] - table[clnm]['Q1']
    table[clnm]['lesser out']= dataset.describe()[clnm]['25%'] - (1.5* table[clnm]['IQR'])
    table[clnm]['greater out']= dataset.describe()[clnm]['75%'] + (1.5* table[clnm]['IQR'])
    table[clnm]["kurtosis"]=dataset[clnm].kurtosis()
    table[clnm]["skew"]=dataset[clnm].skew()
    table[clnm]["var"]=dataset[clnm].var()
    table[clnm]["std"]=dataset[clnm].std()

In [22]:
table

,age,gender,chestpain,restingBP,serumcholestrol,fastingbloodsugar,restingrelectro,maxheartrate,exerciseangia,oldpeak,slope,noofmajorvessels,target
mean,49.242,0.765,0.98,151.747,311.447,0.296,0.748,145.477,0.498,2.7077,1.54,1.222,0.58
median,49.0,1.0,1.0,147.0,318.0,0.0,1.0,146.0,0.0,2.4,2.0,1.0,1.0
mode,20,1,0,127,0,0,0,186,0,2.4,2,1,1
Q1,34.0,1.0,0.0,129.0,235.75,0.0,0.0,119.75,0.0,1.3,1.0,0.0,0.0
Q2,49.0,1.0,1.0,147.0,318.0,0.0,1.0,146.0,0.0,2.4,2.0,1.0,1.0
Q3,64.25,1.0,2.0,181.0,404.25,1.0,1.0,175.0,1.0,4.1,2.0,2.0,1.0
Q4,80.0,1.0,3.0,200.0,602.0,1.0,2.0,202.0,1.0,6.2,3.0,3.0,1.0
IQR,30.25,0.0,2.0,52.0,168.5,1.0,1.0,55.25,1.0,2.8,1.0,2.0,1.0
lesser out,-11.375,1.0,-3.0,51.0,-17.0,-1.5,-1.5,36.875,-1.5,-2.9,-0.5,-3.0,-1.5
min,20,0,0,94,0,0,0,71,0,0.0,0,0,0
greater out,109.625,1.0,5.0,259.0,657.0,2.5,2.5,257.875,2.5,8.3,3.5,5.0,2.5
max,80,1,3,200,602,1,2,202,1,6.2,3,3,1
kurtosis,-1.222831,-0.433663,-1.230535,-1.096546,-0.068486,-1.201171,-1.177253,-0.889123,-2.003948,-1.009874,-1.067692,-0.946674,-1.898394
skew,0.028408,-1.251882,0.345702,0.020204,-0.307025,0.895118,0.465389,-0.251154,0.008012,0.302066,-0.053399,0.291179,-0.324664
var,319.148585,0.179955,0.908509,897.914906,17541.360552,0.208593,0.593089,1168.974445,0.250246,2.960992,1.007407,0.955672,0.243844
std,17.86473,0.424211,0.953157,29.965228,132.443801,0.456719,0.770123,34.190268,0.500246,1.720753,1.003697,0.977585,0.493805

In [12]:
lesser_diff=[]
greater_diff=[]

In [13]:
for clnm in dataset.columns:
    if table[clnm]['lesser out'] > table[clnm]['min']:
        lesser_diff.append(clnm)
    if table[clnm]['max'] > table[clnm]['greater out']:
        greater_diff.append(clnm)

In [14]:
#outlier found in gender column. it can be avoided
lesser_diff

['gender']

In [15]:
greater_diff

[]

In [23]:
#frequency
def freq (clnm,dataset):
    
    freqtab= pd.DataFrame(columns=['unique_values','frequency','rel_frequency','cum_frequency'])
   
    freqtab ['unique_values'] = dataset[clnm].value_counts().index 
    freqtab ['frequency'] = dataset[clnm].value_counts().values
    freqtab ['rel_frequency'] = freqtab ['frequency']/dataset[clnm].count()
    freqtab ['cum_frequency'] = freqtab ['rel_frequency'].cumsum()
    
    return freqtab

In [25]:
freq('target',dataset)

   unique_values  frequency  rel_frequency  cum_frequency
0              1        580           0.58           0.58
1              0        420           0.42           1.00